apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payment-service-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/tharaneshtharanesh431-design/DevOps_26_Exercises.git
    targetRevision: HEAD
    path: exercise-20-external-secrets # Demo folder reference
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  # FIX: Ignore differences in replicas fields when HPA controls the scale
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
