# Logrotate configuration for containerd / EKS container log files
/var/log/pods/*/*.log
/var/log/pods/*/*/*.log
/var/log/containers/*.log {
    hourly
    rotate 5
    copytruncate
    compress
    delaycompress
    missingok
    notifempty
    maxsize 10M
    sharedscripts
}
