apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: payment-db-externalsecret
  namespace: default
  labels:
    app.kubernetes.io/name: payment-db-externalsecret
    app.kubernetes.io/component: credential-management
    app.kubernetes.io/part-of: payment-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: payment-db-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: prod/payment/secrets
        property: DB_USERNAME
    - secretKey: DB_PASSWORD
      remoteRef:
        key: prod/payment/secrets
        property: DB_PASSWORD
    - secretKey: JWT_SECRET
      remoteRef:
        key: prod/payment/secrets
        property: JWT_SECRET
