apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Chart.Name }}-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: {{ .Chart.Name }}-k8s-secret
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: prod/payment/secrets
        property: DB_PASSWORD

