apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-servicemonitor
  namespace: default
spec:
  selector:
    matchLabels:
      app: payment-service
  endpoints:
    - port: metrics
      path: /metrics

